apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: logging
data:
  elasticsearch.yml: |
    cluster.name: elasticsearch
    network.host: 0.0.0.0
    discovery.seed_hosts: elasticsearch
    cluster.initial_master_nodes: elasticsearch-0,elasticsearch-1,elasticsearch-2
    xpack.security.enabled: true
    xpack.security.transport.ssl.enabled: true
    xpack.security.http.ssl.enabled: true 