apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: logging
  labels:
    app: logstash
spec:
  ports:
  - port: 5044
    name: beats
    targetPort: 5044
  - port: 5000
    name: tcp
    targetPort: 5000
  - port: 9600
    name: http
    targetPort: 9600
  selector:
    app: logstash 