apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: nginx:latest  # Replace with your application image
        ports:
        - containerPort: 80
        volumeMounts:
        - name: web-app-storage
          mountPath: /usr/share/nginx/html  # Replace with your application's data directory
      volumes:
      - name: web-app-storage
        persistentVolumeClaim:
          claimName: web-app-pvc-poc
---
apiVersion: v1
kind: Service
metadata:
  name: web-app-service
spec:
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30888
  type: NodePort

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-app-pvc-poc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Mi