apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: opensearch
  namespace: logging
spec:
  general:
    serviceName: opensearch
    version: 2.11.0
  dashboards:
    enable: true
    version: 2.11.0
    replicas: 1
    resources:
      requests:
        memory: "1Gi"
        cpu: "1"
      limits:
        memory: "2Gi"
        cpu: "2"
  nodePools:
  - component: masters
    replicas: 3
    diskSize: "20Gi"
    storageClass: longhorn
    resources:
      requests:
        memory: "2Gi"
        cpu: "1"
      limits:
        memory: "4Gi"
        cpu: "2"
    roles:
      - "master"
      - "data"
      - "ingest"
    persistence:
      enabled: true
      pvc:
        accessModes:
          - ReadWriteOnce
        storageClassName: longhorn
        size: 20Gi
  security:
    tls:
      transport:
        generate: true
      http:
        generate: true
    config:
      enabled: true
      tls:
        transport:
          enabled: true
        http:
          enabled: true 