apiVersion: v1
kind: Service
metadata:
  name: opensearch
  namespace: logging
  labels:
    app: opensearch
spec:
  ports:
  - port: 9200
    name: http
    targetPort: 9200
  - port: 9600
    name: transport
    targetPort: 9600
  selector:
    opensearch.opster.io/cluster-name: opensearch
---
apiVersion: v1
kind: Service
metadata:
  name: opensearch-dashboards
  namespace: logging
  labels:
    app: opensearch-dashboards
spec:
  ports:
  - port: 5601
    name: http
    targetPort: 5601
  selector:
    opensearch.opster.io/cluster-name: opensearch
    opensearch.opster.io/component: dashboards 