apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: database
  labels:
    app: postgresql
spec:
  ports:
  - port: 5432
    name: postgresql
    targetPort: 5432
  selector:
    cnpg.io/cluster: postgresql 