apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: simple-cluster
  namespace: database
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:15.4
  enableSuperuserAccess: true
  storage:
    storageClass: longhorn
    size: 5Gi
  superuserSecret:
    name: pg-superuser-secret
