apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: database
spec:
  selector:
    app: redis
  ports:
  - port: 30000
    targetPort: 6379
    nodePort: 30000
    protocol: TCP
  type: NodePort